from nonebot.adapters.onebot.v11 import GROUP, GROUP_ADMIN, GROUP_OWNER, PRIVATE
from nonebot.permission import SUPERUSER, Permission, USER

ADMIN = SUPERUSER | GROUP_ADMIN | GROUP_OWNER
PADMIN = SUPERUSER | GROUP_ADMIN | GROUP_OWNER | PRIVATE
OWNER = SUPERUSER | GROUP_OWNER
POWNER = SUPERUSER | GROUP_OWNER | PRIVATE
NORMAL = SUPERUSER | GROUP | PRIVATE
