"""Platform abstraction — OB11-shaped helpers + generic send/target"""

# Re-export commonly-used Alconna/command symbols for backward compat
from hoshino.command import (
    Alconna as Alconna,
    Args as Args,
    At as At,
    CommandMeta as CommandMeta,
    UniMsg as UniMsg,
    uni_image as uni_image,
    uni_text as uni_text,
    uni_video as uni_video,
)

from .bot import (
    get_group_list,
    get_group_member_info,
    send_group_forward,
    send_private_forward,
    upload_group_file,
)
from .ob11.event import (
    get_event_message,
    get_event_value,
    get_group_id,
    get_message_id,
    get_plaintext,
    get_reply_message,
    get_session_id,
    get_user_id,
    is_group_event,
    is_message_event,
    is_private_event,
)
from .message import (
    MessageLike,
    Target,
    UniMessage,
    custom_node_segment,
    image_segment,
    message_from_parts,
    send_to_event,
    send_to_event_or_fallback,
    send_to_target,
    text_message,
    to_unimessage,
    video_segment,
)
from .target import (
    dump_target,
    event_scope_key,
    group_target,
    group_scope_key,
    load_target,
    load_target_or_group,
    platform_key,
    private_target,
    target_from_event,
    target_scope_key,
)

__all__ = [
    "MessageLike",
    "Target",
    "UniMessage",
    "custom_node_segment",
    "dump_target",
    "event_scope_key",
    "get_event_message",
    "get_event_value",
    "get_group_id",
    "get_group_list",
    "get_group_member_info",
    "get_message_id",
    "get_plaintext",
    "get_reply_message",
    "get_session_id",
    "get_user_id",
    "group_target",
    "group_scope_key",
    "image_segment",
    "is_group_event",
    "is_message_event",
    "is_private_event",
    "load_target",
    "load_target_or_group",
    "message_from_parts",
    "platform_key",
    "private_target",
    "send_group_forward",
    "send_private_forward",
    "send_to_event",
    "send_to_event_or_fallback",
    "send_to_target",
    "target_from_event",
    "target_scope_key",
    "text_message",
    "to_unimessage",
    "upload_group_file",
    "video_segment",
]
