"""Platform abstraction — OB11-shaped helpers + generic send/target"""

from .depends import LightAPPJsonPayload, LightAppJsonPayload
from .bot import (
    get_group_list,
    get_group_member_info,
    get_media_download_headers,
    get_media_url,
    send_group_forward,
    send_private_forward,
    upload_group_file,
)
from .event import (
    get_event_message,
    get_event_value,
    get_forwarded_messages,
    get_group_id,
    get_message_id,
    get_plaintext,
    get_reply_content,
    get_reply_message,
    get_reply_message_id,
    get_reply_sender_id,
    get_session_id,
    get_user_id,
    is_group_event,
    is_message_event,
    is_private_event,
    is_reply_to_bot,
)
from .forward import forward_reacted_message
from .message import (
    MessageLike,
    Target,
    UniMessage,
    custom_node_segment,
    image_segment,
    message_from_parts,
    send_to_event,
    send_to_event_or_fallback,
    send_to_target,
    text_message,
    to_unimessage,
    video_segment,
)
from .models import ReactionInfo, RetrievedMessage
from .superuser import (
    adapter_superuser_prefix,
    is_superuser,
    send_to_superuser,
    superuser_ids_for_bot,
    superuser_key,
)
from .reaction import (
    ReactedMessage,
    Reaction,
    get_reaction_info,
    is_reaction_event,
    reaction_event_rule,
)
from .target import (
    dump_target,
    event_scope_key,
    group_scope_key,
    group_target,
    load_target,
    load_target_or_group,
    platform_key,
    private_target,
    target_from_event,
    target_scope_key,
)

__all__ = [
    "LightAPPJsonPayload",
    "LightAppJsonPayload",
    "MessageLike",
    "ReactionInfo",
    "RetrievedMessage",
    "adapter_superuser_prefix",
    "is_superuser",
    "send_to_superuser",
    "Target",
    "UniMessage",
    "custom_node_segment",
    "dump_target",
    "event_scope_key",
    "forward_reacted_message",
    "get_event_message",
    "get_event_value",
    "get_forwarded_messages",
    "get_group_id",
    "get_group_list",
    "get_group_member_info",
    "get_message_id",
    "get_media_download_headers",
    "get_media_url",
    "get_plaintext",
    "get_reply_content",
    "get_reply_message",
    "get_reply_message_id",
    "get_reply_sender_id",
    "get_session_id",
    "get_user_id",
    "group_target",
    "group_scope_key",
    "image_segment",
    "is_group_event",
    "is_message_event",
    "is_private_event",
    "is_reaction_event",
    "is_reply_to_bot",
    "load_target",
    "load_target_or_group",
    "message_from_parts",
    "platform_key",
    "private_target",
    "ReactedMessage",
    "Reaction",
    "get_reaction_info",
    "reaction_event_rule",
    "send_group_forward",
    "send_private_forward",
    "send_to_event",
    "send_to_event_or_fallback",
    "send_to_target",
    "superuser_ids_for_bot",
    "superuser_key",
    "target_from_event",
    "target_scope_key",
    "text_message",
    "to_unimessage",
    "upload_group_file",
    "video_segment",
]
